### ISSUE TITLE
Construct URLs with functions

### ISSUE THREAD

**Issue by bogosj** [bogosj/tesla#35]
i.e. `path.Join(u.Path, "vehicles", strconv.FormatUint(id, 10), "vehicle_data")`

**Comment by michaelharo** [comment]
I think most of that can be handled in the Vehicle struct using a function that calculates most of it so that the call becomes something like `v.path("vehicle_data")` and it returns the full path.

**Comment by bogosj** [comment]
Yep, that was the approach I was going to take. Low priority so waiting for the other PRs to land and maybe even v1.0 tag before doing this since it's internal cleanup.
