### ISSUE TITLE
Missing semver tag?

### ISSUE THREAD

**Issue by andig** [bogosj/tesla#51]
When I upgrade to latest version, I do not get an update:

    ❯ go get -v github.com/bogosj/tesla@latest

`go.mod` remains at:

	github.com/bogosj/tesla v0.0.0-20210425155839-8493aa0dee71

I'm wondering if that's due to the tag being `1.0` instead of `1.0.0` which would be correct semver?

**Comment by bogosj** [comment]
That appears to have been the problem. v1.0.0 tag created, v1.0 deleted.
