### ISSUE TITLE
Unable to authenticate using cmd/login

### ISSUE THREAD

**Issue by Rudi9719** [bogosj/tesla#56]
Was writing a bot and accidentally logged out. Now I can't seem to log back in using my old code, or the cmd/login example.

```
╭─rudi@imogene ~/tesla/cmd/login  ‹main› 
╰─➤  go run . -o tesla.token
Username: rudi@nightmare.haus
Password: ************************************************************
2021/07/10 11:06:37 list devices: do: Get "https://auth.tesla.com/oauth2/v3/authorize/mfa/factors?transaction_id=[redacted]": net/http: timeout awaiting response headers
exit status 1
```

**Comment by Rudi9719** [comment]
Was able to authenticate using a token generated from a 3rd party, but not using cmd/login

**Comment by andig** [comment]
Same report here: https://github.com/andig/evcc/discussions/1201. I suspect Tesla may have reactivated the captcha, potentially only when MFA is NOT used?

**Comment by andig** [comment]
Teslamate has done https://github.com/adriankumpf/teslamate/commit/1a90cdeadfa5dfe57a78aa8c4cad517f3d0b775a

**Comment by andig** [comment]
https://github.com/fkhera/powerwallCloud/commit/ba4012a4d6b6cfd0f5fd8d8299577fca005bb42f has a process of:
- convert captcha from svg to png
- use 2captcha to solve (requires API key)
- use result

**Comment by Rudi9719** [comment]
I've noticed a few other apps having issue with Tesla auth recently.
