### ISSUE TITLE
Support /api/products

### ISSUE THREAD

**Issue by andig** [bogosj/tesla#88]
https://github.com/evcc-io/evcc/discussions/5826#discussioncomment-4722048 has an interesting discussion on how to remote control a powerwall. Access is via Tesla api credentials that we have. It would be nice to provide read-only and potentially write access to the broader Tesla api beyond vehicles.

**Comment by GrimmiMeloni** [comment]
@bogosj I intend to add this (for the reason state above by @andig) in the coming days. Would appreciate if you could assign this to me.

**Comment by andig** [comment]
@GrimmiMeloni no longer worth it. Tesla has sunset the api.

**Comment by GrimmiMeloni** [comment]
Oh. Is there an end date already defined? Asking because it still works for me _right now_ - but maybe that will go away soon? Any words on replacements?

**Comment by andig** [comment]
See https://github.com/evcc-io/evcc/issues/10460

**Comment by bogosj** [comment]
@andig - I only took a brief look at https://github.com/teslamotors/vehicle-command - am I reading this correctly that ultimately bogosj/tesla will ultimately be deprecated in favor of this new method? As of now anything using bogosj/tesla can use the proxy provided in the teslamotors repo but if you're building something new you should probably use that directly?

**Comment by andig** [comment]
I still haven't got it implemented, so no definite answer. It seems the struct definitions are (still) not par of the vehicle-command API. Not sure if those will be the same though. The entire auth should go away...

**Comment by GrimmiMeloni** [comment]
The tesla repo mentions that pre-2021 models will still use the old owners API. So my understanding is that the API will stay for now, however newer car models will only be accessible via their new SDK. 
I hope the same is true for older energy products like the existing Powerwalls.
